# Generated by Django 4.1 on 2022-09-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image_like_comment'),
        ('posts', '0003_add_post_title'),
    ]

    operations = [
    ]
